"""Add RFPProject model

Revision ID: 3da125cc992d
Revises: e3aa23c2efba
Create Date: 2026-09-02 20:26:01.501798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da125cc992d'
down_revision: Union[str, Sequence[str], None] = 'e3aa23c2efba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_contact', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUBMITTED', 'AWARDED', 'LOST', 'ARCHIVED', name='projectstatusenum'), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference_number', name='uq_org_ref_number')
    )
    op.create_index(op.f('ix_rfp_project_created_by_id'), 'rfp_project', ['created_by_id'], unique=False)
    op.create_index('ix_rfp_project_org_created', 'rfp_project', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_rfp_project_org_status', 'rfp_project', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_rfp_project_organization_id'), 'rfp_project', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfp_project_organization_id'), table_name='rfp_project')
    op.drop_index('ix_rfp_project_org_status', table_name='rfp_project')
    op.drop_index('ix_rfp_project_org_created', table_name='rfp_project')
    op.drop_index(op.f('ix_rfp_project_created_by_id'), table_name='rfp_project')
    op.drop_table('rfp_project')
    # ### end Alembic commands ###
