"""Add RFPDocument and DocumentVersion models

Revision ID: 604df9fc7238
Revises: 3da125cc992d
Create Date: 2026-09-02 20:39:55.139141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604df9fc7238'
down_revision: Union[str, Sequence[str], None] = '3da125cc992d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rfp_project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'DOCX', 'XLSX', 'PPTX', name='documenttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='documentstatusenum'), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_version.id'], name='fk_rfp_document_current_version_id', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['rfp_project_id'], ['rfp_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_document_organization_id'), 'rfp_document', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rfp_document_rfp_project_id'), 'rfp_document', ['rfp_project_id'], unique=False)
    op.create_table('document_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rfp_document_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['rfp_document_id'], ['rfp_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfp_document_id', 'version_number', name='uq_doc_version_number')
    )
    op.create_index(op.f('ix_document_version_organization_id'), 'document_version', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_version_rfp_document_id'), 'document_version', ['rfp_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_version_rfp_document_id'), table_name='document_version')
    op.drop_index(op.f('ix_document_version_organization_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_rfp_document_rfp_project_id'), table_name='rfp_document')
    op.drop_index(op.f('ix_rfp_document_organization_id'), table_name='rfp_document')
    op.drop_table('rfp_document')
    # ### end Alembic commands ###
