"""add_phase_9_compliance_models

Revision ID: d788b82de69a
Revises: 41611b194e14
Create Date: 2026-09-16 20:42:25.886627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd788b82de69a'
down_revision: Union[str, Sequence[str], None] = '41611b194e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rfp_project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('COMPLIANT', 'PARTIALLY_COMPLIANT', 'NON_COMPLIANT', 'UNKNOWN', 'REVIEW_REQUIRED', name='compliancestatusenum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('unsupported_claims', sa.Text(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='reviewstatusenum'), nullable=False),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rfp_project_id'], ['rfp_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessment_organization_id'), 'compliance_assessment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessment_requirement_id'), 'compliance_assessment', ['requirement_id'], unique=True)
    op.create_index(op.f('ix_compliance_assessment_review_required'), 'compliance_assessment', ['review_required'], unique=False)
    op.create_index(op.f('ix_compliance_assessment_review_status'), 'compliance_assessment', ['review_status'], unique=False)
    op.create_index(op.f('ix_compliance_assessment_rfp_project_id'), 'compliance_assessment', ['rfp_project_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessment_status'), 'compliance_assessment', ['status'], unique=False)
    op.create_table('compliance_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('authority_level', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('is_conflicting', sa.Boolean(), nullable=False),
    sa.Column('conflict_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessment.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_evidence_assessment_id'), 'compliance_evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_organization_id'), 'compliance_evidence', ['organization_id'], unique=False)
    op.create_table('gap_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('missing_capability', sa.Text(), nullable=False),
    sa.Column('gap_severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='gapseverityenum'), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessment.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analysis_assessment_id'), 'gap_analysis', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_gap_analysis_gap_severity'), 'gap_analysis', ['gap_severity'], unique=False)
    op.create_index(op.f('ix_gap_analysis_organization_id'), 'gap_analysis', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gap_analysis_requirement_id'), 'gap_analysis', ['requirement_id'], unique=False)
    op.create_table('risk_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('risk_category', sa.Enum('TECHNICAL', 'COMPLIANCE', 'DELIVERY', 'COMMERCIAL', 'OPERATIONAL', 'INFORMATION', 'UNKNOWN', name='riskcategoryenum'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='riskseverityenum'), nullable=False),
    sa.Column('likelihood', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('mitigation_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessment.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_analysis_assessment_id'), 'risk_analysis', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_risk_analysis_organization_id'), 'risk_analysis', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_analysis_requirement_id'), 'risk_analysis', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_risk_analysis_risk_category'), 'risk_analysis', ['risk_category'], unique=False)
    op.create_index(op.f('ix_risk_analysis_severity'), 'risk_analysis', ['severity'], unique=False)
    op.drop_constraint(op.f('document_content_document_version_id_key'), 'document_content', type_='unique')
    op.drop_index(op.f('ix_document_content_document_version_id'), table_name='document_content')
    op.create_index(op.f('ix_document_content_document_version_id'), 'document_content', ['document_version_id'], unique=True)
    op.alter_column('knowledge_chunk', 'source_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_knowledge_chunk_search_vector'), table_name='knowledge_chunk', postgresql_using='gin')
    op.drop_constraint(op.f('knowledge_chunk_knowledge_document_id_fkey'), 'knowledge_chunk', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_chunk_knowledge_version_id_fkey'), 'knowledge_chunk', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunk', 'company_knowledge_document', ['knowledge_document_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_chunk', 'knowledge_document_version', ['knowledge_version_id'], ['id'])
    op.drop_constraint(op.f('knowledge_document_version_knowledge_document_id_fkey'), 'knowledge_document_version', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_document_version', 'company_knowledge_document', ['knowledge_document_id'], ['id'])
    op.alter_column('previous_proposal_section', 'source_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_previous_proposal_section_search_vector'), table_name='previous_proposal_section', postgresql_using='gin')
    op.drop_constraint(op.f('previous_proposal_section_proposal_version_id_fkey'), 'previous_proposal_section', type_='foreignkey')
    op.drop_constraint(op.f('previous_proposal_section_proposal_id_fkey'), 'previous_proposal_section', type_='foreignkey')
    op.create_foreign_key(None, 'previous_proposal_section', 'previous_proposal_version', ['proposal_version_id'], ['id'])
    op.create_foreign_key(None, 'previous_proposal_section', 'previous_proposal', ['proposal_id'], ['id'])
    op.drop_constraint(op.f('previous_proposal_version_previous_proposal_id_fkey'), 'previous_proposal_version', type_='foreignkey')
    op.create_foreign_key(None, 'previous_proposal_version', 'previous_proposal', ['previous_proposal_id'], ['id'])
    op.drop_constraint(op.f('requirement_evidence_requirement_id_fkey'), 'requirement_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'requirement_evidence', 'requirement', ['requirement_id'], ['id'])
    op.create_foreign_key('fk_rfp_document_current_version_id', 'rfp_document', 'document_version', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rfp_document_current_version_id', 'rfp_document', type_='foreignkey')
    op.drop_constraint(None, 'requirement_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('requirement_evidence_requirement_id_fkey'), 'requirement_evidence', 'requirement', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'previous_proposal_version', type_='foreignkey')
    op.create_foreign_key(op.f('previous_proposal_version_previous_proposal_id_fkey'), 'previous_proposal_version', 'previous_proposal', ['previous_proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'previous_proposal_section', type_='foreignkey')
    op.drop_constraint(None, 'previous_proposal_section', type_='foreignkey')
    op.create_foreign_key(op.f('previous_proposal_section_proposal_id_fkey'), 'previous_proposal_section', 'previous_proposal', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('previous_proposal_section_proposal_version_id_fkey'), 'previous_proposal_section', 'previous_proposal_version', ['proposal_version_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_previous_proposal_section_search_vector'), 'previous_proposal_section', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('previous_proposal_section', 'source_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'knowledge_document_version', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_document_version_knowledge_document_id_fkey'), 'knowledge_document_version', 'company_knowledge_document', ['knowledge_document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'knowledge_chunk', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_chunk', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_chunk_knowledge_version_id_fkey'), 'knowledge_chunk', 'knowledge_document_version', ['knowledge_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('knowledge_chunk_knowledge_document_id_fkey'), 'knowledge_chunk', 'company_knowledge_document', ['knowledge_document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_knowledge_chunk_search_vector'), 'knowledge_chunk', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('knowledge_chunk', 'source_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_document_content_document_version_id'), table_name='document_content')
    op.create_index(op.f('ix_document_content_document_version_id'), 'document_content', ['document_version_id'], unique=False)
    op.create_unique_constraint(op.f('document_content_document_version_id_key'), 'document_content', ['document_version_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_risk_analysis_severity'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_risk_category'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_requirement_id'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_organization_id'), table_name='risk_analysis')
    op.drop_index(op.f('ix_risk_analysis_assessment_id'), table_name='risk_analysis')
    op.drop_table('risk_analysis')
    op.drop_index(op.f('ix_gap_analysis_requirement_id'), table_name='gap_analysis')
    op.drop_index(op.f('ix_gap_analysis_organization_id'), table_name='gap_analysis')
    op.drop_index(op.f('ix_gap_analysis_gap_severity'), table_name='gap_analysis')
    op.drop_index(op.f('ix_gap_analysis_assessment_id'), table_name='gap_analysis')
    op.drop_table('gap_analysis')
    op.drop_index(op.f('ix_compliance_evidence_organization_id'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_assessment_id'), table_name='compliance_evidence')
    op.drop_table('compliance_evidence')
    op.drop_index(op.f('ix_compliance_assessment_status'), table_name='compliance_assessment')
    op.drop_index(op.f('ix_compliance_assessment_rfp_project_id'), table_name='compliance_assessment')
    op.drop_index(op.f('ix_compliance_assessment_review_status'), table_name='compliance_assessment')
    op.drop_index(op.f('ix_compliance_assessment_review_required'), table_name='compliance_assessment')
    op.drop_index(op.f('ix_compliance_assessment_requirement_id'), table_name='compliance_assessment')
    op.drop_index(op.f('ix_compliance_assessment_organization_id'), table_name='compliance_assessment')
    op.drop_table('compliance_assessment')
    # ### end Alembic commands ###
